### ISSUE TITLE
VLAN Interface Errors

### ISSUE THREAD

**Issue by tomatotoast** [opnsense/src#74] opened 2020-08-01 16:15 UTC
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[X] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md

[X] I have searched the existing issues and I'm convinced that mine is new.

**Describe the bug**
A clear and concise description of what the bug is, including last known working version (if any).

I just upgraded a box from 20.1 to 20.7 Since the upgrade I can detect errors on the VLANs. On the side of the switch I could not detect any errors.

*Tip*: to validate your setup was working with the previous version, use opnsense-revert (https://docs.opnsense.org/manual/opnsense_tools.html#opnsense-revert)

**To Reproduce**
1. Use box with igb NICs and 20.1
2. Create VLAN on Parent Interface and create some Traffic, All interface Errors should be "0"
3. Upgrade to 20.7
4. Look at Interface Errors

**Expected behavior**
Like in 20.1 in 20.7 there should be no Errors on the VLAN Interfaces

**Screenshots**
![grafik](https://user-images.githubusercontent.com/60579201/89105588-94e16f00-d422-11ea-983b-6ed98e7dbfba.png)
![grafik](https://user-images.githubusercontent.com/60579201/89105593-99a62300-d422-11ea-85f6-f28225b0994d.png)

**Relevant log files**
If applicable, information from log files supporting your claim.

**Additional context**

**Environment**
Software version used and hardware type if relevant.
e.g.:

OPNsense 20.7-amd64
FreeBSD 12.1-RELEASE-p7-HBSD
OpenSSL 1.1.1g 21 Apr 2020

    vendor     = 'Intel Corporation'
    device     = 'I211 Gigabit Network Connection'
    class      = network
    subclass   = ethernet

**Comment by tomatotoast** [comment] 2020-09-03 09:55
> Should be fixed in 20.7.2. If you guys could confirm that would be great.

I cant confirm this.
The issue still exists.

**Comment by fichtner** [comment] 2020-09-03 10:53
Can you confirm that these are non-legit errors? I'm not sure what the hypothesis is then?

**Comment by tomatotoast** [comment] 2020-09-03 15:05
> Can you confirm that these are non-legit errors? I'm not sure what the hypothesis is then?

I dont like to upset you, but this is after updating to:

OPNsense 20.7.2-amd64
FreeBSD 12.1-RELEASE-p8-HBSD
OpenSSL 1.1.1g 21 Apr 2020

![grafik](https://user-images.githubusercontent.com/60579201/92132449-71d22280-ee07-11ea-9452-a4cd0c9041c9.png)

This is the same hardware as in the first post.

**Comment by fichtner** [comment] 2020-09-03 15:26
You don't ;) But I struggle with how to move further because we are back to square one and I don't particularly enjoy reading driver code changes in order to find another bug hidden there worst case.

**Comment by AdSchellevis** [comment] 2020-09-03 15:38
What stands out is that these always seems to be "out" errors and that the number doesn't seem to be increasing (at least not on my end).  The parent interface doesn't report errors on my end. 

There's likely no need to chase this very quickly, no real life issues seem to be involved as far as I can see.

**Comment by peter-vanpoucke** [comment] 2020-09-05 13:58
The "VMware promisc mode" issue is also solved in 20.7.2.

I didn't check previously, but I do still notice out errors on the VLAN interfaces both with the 20.7.1-nopromisc kernel and in 20.7.2. They're negligible though and, as I checked just before upgrading to 20.7.2, they seem to be as high as they were before restarting/upgrading.

**Comment by fichtner** [comment] 2020-09-05 16:32
As @AdSchellevis noted this would likely fix spurious incoming errors, not outgoing errors.

**Comment by swhite2** [comment] 2021-02-12 16:40
I have been able to reproduce the issue in a VirtualBox VM. It seems these errors are caused by automatic link-local address configuration (IPv6). As soon as a VLAN is assigned to an interface (before interface assignment), the link-local configuration thinks it's high time to send out packets over the interface while it's not yet up and running. This causes the vlan transmit function to exit with ENETDOWN and increases the out errors by one for each packet.

The consistency in the above test was that I was only able to reproduce a small number of packet out errors, in a condition where packets would be sent in between VLAN attach and interface UP/running. However, the out errors as depicted above are quite high, giving me the impression this could be a 2-sided problem.

If anyone NOT using IPv6 were to run `sysctl net.inet6.ip6.auto_linklocal=0`, observe whether it fixes the errors long-term and provide some feedback, that would be great :)

**Comment by bsd-source** [comment] 2021-02-14 04:32
msi-x related?

**Comment by swhite2** [comment] 2021-02-14 16:07
> msi-x related?

I'm not entirely sure what you mean by msi-x in this context. If you are referring to hardware; the errors have not been observed to be hardware related, no collision events have occurred. If there was a problem with msi-x, the interface would be unusable. Any other 'out errors' on the transmit side are always generated before a soft-interrupt inside the kernel.

There is one possibility for a transmit queue to be hung, if that is the case there should be an error logged in dmesg - not the case in my setup (no watchdog events registered).

What I'm trying to assert here is that errors **only** occur when assigning a VLAN tag to an interface, not after it has already been assigned.  

If the errors only occur when setting up the VLAN tag, it will be related to an out-of-order sequence of initialization events inside the kernel.

**Comment by cbrueffer** [comment] 2021-02-24 17:07
Thanks for the analysis; I'll be able to test your suggestion next week.

**Comment by swhite2** [comment] 2021-02-25 07:57
> Thanks for the analysis; I'll be able to test your suggestion next week.

You're welcome, looking forward to it.

**Comment by cbrueffer** [comment] 2021-02-28 21:03
I tested @swhite2's proposed fix/workaround, and while it may have helped (numbers seem lower) it hasn't fixed the issue completely for me; see screenshot. Interfaces from left to right are DMZ, VLAN1, VLAN2, VLAN3, WAN.

![Screenshot_2021-02-28_22-02-45](https://user-images.githubusercontent.com/2705287/109433467-b7675500-7a10-11eb-8828-9504c853d448.png)

**Comment by swhite2** [comment] 2021-03-01 09:41
@cbrueffer Thanks for the feedback, it seems there are at least two issues causing this. Have the errors gone up since interface assignment? Or do they appear fixed?

**Comment by cbrueffer** [comment] 2021-03-01 09:53
Errors have stayed the same since rebooting yesterday.

**Comment by fichtner** [comment] 2022-01-31 07:47
New FreeBSD major version being used now and I'm closing this.

**Closed by fichtner** 2022-01-31 07:47 UTC
Labels: upstream
