### ISSUE TITLE
Can't delete route in 24.10.1, "gateway uses the same route", FreeBSD bug 279988

### ISSUE THREAD

**Issue by abruening-iwt** [opnsense/src#229] opened 2024-11-29 16:28 UTC
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [X ] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [X ] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**

Attempting to remove an auto-generated route, in this case for our dedicated management network interface, results in "gateway uses the same route" on the terminal, the action failing silently in the GUI (/ui/diagnostics/interface/routes)

Example command: route del -4 -net "10.100.0.0/16" -interface ixl0

It worked on OPNSense 24.4.3

**To Reproduce**

1. Go to /ui/diagnostics/interface/routes
2. Click on trash can next to route
3. Reload page

**Expected behavior**

The route should be gone

**Describe alternatives you considered**

Using a copy of /sbin/route from 24.4.3 allows deleting the route.

**Additional context**

This appears to be a FreeBSD bug, there is a single-line fix available here:

https://reviews.freebsd.org/D46301

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279988

**Comment by fichtner** [comment] 2024-11-29 20:18
Intresting... this looks like it was also tracked in https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=277125 and committed in https://cgit.freebsd.org/src/commit/?id=1da4954c92ea7585b352ba830d3ee64ca69ada52 but then they said that tests fail... let me check main to see what happened then

**Comment by fichtner** [comment] 2024-11-29 20:21
it should have been mfc'ed by now but wasn't, may be circumstantial but let's pull it and provide a test kernel

**Comment by fichtner** [comment] 2024-11-29 20:21
69961c43fd24

**Comment by fichtner** [comment] 2024-12-02 07:53
@abruening-iwt Can you try this kernel?

    # opnsense-update -zkr 24.7.8-sfxge

(It's for a panic in the sfxge(4) driver but it includes said commit)


Cheers,
Franco

**Comment by abruening-iwt** [comment] 2024-12-02 11:27
> ```
> # opnsense-update -zkr 24.7.8-sfxge
> ```

```
Fetching kernel-24.7.8-sfxge-amd64.txz: ..[fetch: https://opnsense-update.deciso.com/a7c97462-2d55-4451-b0b2-678e5cdeb7e2/FreeBSD:14:amd64/snapshots/sets/kernel-24.7.8-sfxge-amd64.txz.sig: Not Found] failed, no signature found
```

Has the mirror not caught up or do I need to do something else?

**Comment by fichtner** [comment] 2024-12-02 11:47
Sorry didn't catch the fact you were on the business edition when responding with the test kernel. I can share the kernel over there if you want?

**Comment by abruening-iwt** [comment] 2024-12-02 11:57
As long as there is a way to go back to the standard kernel I can test it, sure.

**Comment by fichtner** [comment] 2024-12-02 12:06
Ok, it's there now using the same command. To go back to standard kernel:

    # opnsense-update -k

(or use the GUI to reinstall the kernel)


Cheers,
Franco

**Comment by abruening-iwt** [comment] 2024-12-02 12:28
Thank you! It doesn't seem to have done the trick though:

```
root@iwt-fw-2:~ # route del -4 -net "10.100.0.0/16" -interface ixl0
del net 10.100.0.0: gateway ixl0 fib 0: gateway uses the same route
root@iwt-fw-2:~ # uname -a
FreeBSD iwt-fw-2.iwt.zz 14.1-RELEASE-p6 FreeBSD 14.1-RELEASE-p6 sfxge_fix-n267972-6c68c771c88 SMP amd64
```

**Comment by fichtner** [comment] 2024-12-02 12:31
That's a bit strange. Might be another edge case. Can you show the conflicting route?

**Comment by abruening-iwt** [comment] 2024-12-02 12:55
Partial `netstat -rn`

```
Internet:
Destination        Gateway            Flags     Netif Expire
default            [Public IP removed]     UGS        ixl2
10.100.0.0/16      link#1             U          ixl0
10.100.0.169       link#5             UHS         lo0
10.100.0.179       link#5             UHS         lo0
```

The one after default is the one to be removed. What it isn't showing is that there's a VLAN interface (from the trunk port) using 10.100.0.0/15, that one acts as the gateway for connected clients. ixl0 is only the management interface and shouldn't be involved in routing traffic at all, that's why I don't want it to have any routes set.

**Comment by fichtner** [comment] 2024-12-02 18:31
Might also be netlink related -- I couldn't find an apparent bug in sbin/route that was still pending, but according to you the old binary works which means pre this one https://github.com/freebsd/freebsd-src/commit/c597432e22975f4

**Comment by fichtner** [comment] 2024-12-02 18:54
I've pulled in some commits in sbin/route and sys/netlink from stable/14 but I don't think these are relevant. I can try to reproduce tomorrow but really need to code freeze for 24.7.10 now. Just to let you know.


Cheers,
Franco

**Comment by fichtner** [comment] 2024-12-02 18:56
(also note the fix was for adding a route, not for deleting it so it may be a yet to be found bug)

**Comment by abruening-iwt** [comment] 2024-12-03 09:41
> (also note the fix was for adding a route, not for deleting it so it may be a yet to be found bug)

The links I added to the OP are about deleting as far as I can see:

https://reviews.freebsd.org/D46301

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279988

**Comment by fichtner** [comment] 2024-12-03 09:48
@abruening-iwt correct, but that commit also never made it into FreeBSD due to a probable regression, see https://reviews.freebsd.org/D46301#1079978

I would like to avoid experimenting with things that are not even in a FreeBSD development version. I made a comment over there.

**Comment by fichtner** [comment] 2024-12-03 14:02
ddc2dc3dfd91c8bcd7

    # opnsense-update -zkr 24.7.10-route

**Comment by fichtner** [comment] 2024-12-05 07:33
@abruening-iwt we had to switch around the kernel commits and the -route kernel had a bad commit as well so it's gone. I'll publish the reissued 24.7.10 to the business mirror for you to try in a minute. BRB.

**Comment by abruening-iwt** [comment] 2024-12-06 14:25
> @abruening-iwt we had to switch around the kernel commits and the -route kernel had a bad commit as well so it's gone. I'll publish the reissued 24.7.10 to the business mirror for you to try in a minute. BRB.

What do I need to do to test it?

**Comment by fichtner** [comment] 2024-12-06 15:47
@abruening-iwt sorry, too much going on. here:

    # opnsense-update -zkr  24.7.10


Cheers,
Franco

**Comment by abruening-iwt** [comment] 2024-12-09 18:31
I think it has worked, the route isn't there after rebooting with the new kernel¹ even though the script is using the default `route` command.

1: `FreeBSD iwt-fw-2.iwt.zz 14.1-RELEASE-p6 FreeBSD 14.1-RELEASE-p6 stable/24.7-n267981-8375762712f SMP amd64`

**Comment by fichtner** [comment] 2024-12-09 21:09
Ok, thanks. According to FreeBSD it is the right patch now but it’s still not in FreeBSD. However, having double-checked we can carry the patch and it should ship in 24.10.2 same as you have installed already. So I’m going to close this.


Cheers,
Franco

**Closed as completed by fichtner** 2024-12-09 21:09 UTC
Labels: upstream
